# Generated by Django 5.2 on 2025-05-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('map_url', models.TextField(blank=True, null=True)),
                ('img_url', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('has_sockets', models.BigIntegerField(blank=True, null=True)),
                ('has_toilet', models.BigIntegerField(blank=True, null=True)),
                ('has_wifi', models.BigIntegerField(blank=True, null=True)),
                ('can_take_calls', models.BigIntegerField(blank=True, null=True)),
                ('seats', models.TextField(blank=True, null=True)),
                ('coffee_price', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cafe',
            },
        ),
    ]
